- job:
    name: zuul-website-build
    description: |
      Publishes a draft version of the Zuul website.
    required-projects:
      - openstack-infra/zuul-website
      - openstack-infra/zuul-website-media
    success-url: html/
    run: playbooks/build-site.yaml
    post-run: playbooks/publish-draft-site.yaml
    nodeset:
      nodes: []

- job:
    name: zuul-website-publish
    parent: publish-zuul-website
    description: |
      Publishes the Zuul website.
    required-projects:
      - openstack-infra/zuul-website
      - openstack-infra/zuul-website-media
    run: playbooks/build-site.yaml
    post-run: playbooks/publish-site.yaml
    nodeset:
      nodes: []

- project:
    check:
      jobs:
        - zuul-website-build
    gate:
      queue: zuul-website
      jobs:
        - zuul-website-build
    post:
      jobs:
        - zuul-website-publish
