- name: Copy site to output directory
  copy:
    src: "{{ zuul.projects['openstack-infra/zuul-website'].src_dir }}/www/"
    dest: "{{ output_dir }}"
  copy:
    src: "{{ zuul.projects['openstack-infra/zuul-website-media'].src_dir }}/media/"
    dest: "{{ output_dir }}/media"
