- hosts: localhost
  roles:
    - role: copy-site-to-artifacts
      when: zuul_success | bool
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "/afs/.openstack.org/project/zuul-ci.org/www"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
